# Generated by Django 3.2.13 on 2022-05-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20220512_1301'),
    ]

    operations = [
    ]
