# Generated by Django 3.2.13 on 2022-05-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20220516_1841'),
    ]

    operations = [
       
    ]
