# Generated by Django 4.0.5 on 2022-06-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_auto_20220526_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
