# Generated by Django 4.0.5 on 2022-07-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_delete_customer_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photo',
        ),
    ]
